import React from 'react';
import { businesses, departments, users, taskLibrary, attendance } from '../data/seed';

export function Businesses(){return <TablePage title="Businesses" desc="Multiple businesses manage karne ke liye." rows={businesses} cols={['name','status']}/>}
export function Departments(){return <TablePage title="Departments" desc="Business → Department hierarchy." rows={departments} cols={['name','businessId','managerId']}/>}
export function Employees(){return <TablePage title="Employees" desc="Role, department, team lead mapping." rows={users} cols={['name','email','role','departmentId','teamLeadId']}/>}
export function Attendance(){return <TablePage title="Attendance" desc="Check in, break, checkout, working hours." rows={attendance} cols={['date','userId','checkIn','breakMinutes','checkOut','workingHours','status']}/>}
export function TaskLibrary(){return <TablePage title="Task Library" desc="Admin only master recurring task library." rows={taskLibrary} cols={['code','name','businessId','departmentId','frequency','priority','estimatedMinutes','dependsOn']}/>}
export function Reports(){return <section className="page"><h1>Reports</h1><p className="muted">Employee, Department, Business, Attendance aur Productivity reports yaha expand honge.</p><div className="grid3"><div className="card"><h3>Employee Performance</h3><b className="big">82%</b></div><div className="card"><h3>Department Productivity</h3><b className="big">76%</b></div><div className="card"><h3>Attendance Health</h3><b className="big">91%</b></div></div></section>}
export function Calendar(){return <section className="page"><h1>Calendar</h1><div className="card"><p>Task due dates, attendance, reminders aur review calendar yaha aayega.</p></div></section>}
export function Settings(){return <section className="page"><h1>Settings</h1><div className="card"><h3>System Masters</h3><p>Businesses, departments, roles, priorities, statuses, frequencies, custom fields, versioning.</p><div className="chips darkchips"><span>Version 1.0.0</span><span>Soft Delete Enabled</span><span>Audit Log Ready</span><span>API Ready</span></div></div></section>}
export function Generator(){return <section className="page"><h1>Task Generator</h1><div className="card form"><div><label>Business</label><select><option>SIA Jewels</option><option>SBX Media</option></select></div><div><label>Department</label><select><option>Graphic Design</option><option>Video Editing</option></select></div><div><label>Frequency</label><select><option>Daily</option><option>Weekly</option><option>Monthly</option></select></div><div><label>Employee</label><select><option>Rahul</option><option>Aman</option></select></div><button className="primary">Generate Tasks</button></div></section>}

function TablePage({title, desc, rows, cols}){return <section className="page"><h1>{title}</h1><p className="muted">{desc}</p><div className="card overflow"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{cols.map(c=><td key={c}>{Array.isArray(r[c])?r[c].join(', '):(r[c]??'-')}</td>)}</tr>)}</tbody></table></div></section>}
