import React, {createContext,useContext,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,LayoutDashboard,Briefcase,Users,Layers,CheckSquare,CalendarDays,Clock,BarChart3,Settings,Shield,Plus,Trash2,Archive,Download,Upload,Sun,Moon,Play,Pause,Square,Eye,MessageSquare,Paperclip,History,LogOut} from 'lucide-react';
import {PieChart,Pie,Cell,ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip} from 'recharts';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import './styles.css';

const ROLES={Founder:'all',Admin:'all',Manager:'department',TeamLead:'team',Employee:'self',Intern:'self'};
const statuses=['Ready','In Progress','Review','Revision','Completed'];
const priorities=['Low','Medium','High','Urgent'];
const frequencies=['Daily','Weekly','Monthly','Yearly','Custom'];
const businesses=['SIA Jewels','SBX Media','Westory'];
const departments=['Graphic Design','Video Editing','Social Media','Website','Finance','Customer Support'];
const employees=[
{id:'u1',name:'Sandhya',role:'Founder',department:'All',business:'All',teamId:'t0'},
{id:'u2',name:'Rahul',role:'TeamLead',department:'Graphic Design',business:'SIA Jewels',teamId:'t1'},
{id:'u3',name:'Aman',role:'Employee',department:'Video Editing',business:'SIA Jewels',teamId:'t2'},
{id:'u4',name:'Neha',role:'Employee',department:'Graphic Design',business:'SIA Jewels',teamId:'t1'},
{id:'u5',name:'Priya',role:'Manager',department:'Finance',business:'SBX Media',teamId:'t3'}
];
const librarySeed=[
{id:'LIB-0001',name:'Design Instagram Feed Post',business:'SIA Jewels',department:'Graphic Design',role:'Designer',frequency:'Daily',priority:'High',estimated:30,dependsOn:'-',sop:'https://example.com/sop/feed',checklist:['Open brief','Create design','Send for review'],tags:['social','design']},
{id:'LIB-0002',name:'Design Instagram Story',business:'SIA Jewels',department:'Graphic Design',role:'Designer',frequency:'Daily',priority:'Medium',estimated:20,dependsOn:'-',sop:'https://example.com/sop/story',checklist:['Choose template','Add product','Export'],tags:['story']},
{id:'LIB-0003',name:'Edit Product Reel',business:'SIA Jewels',department:'Video Editing',role:'Editor',frequency:'Daily',priority:'High',estimated:45,dependsOn:'-',sop:'https://example.com/sop/reel',checklist:['Cut footage','Add music','Export reel'],tags:['reel']},
{id:'LIB-0004',name:'Update Sales Report',business:'SBX Media',department:'Finance',role:'Executive',frequency:'Daily',priority:'High',estimated:40,dependsOn:'-',sop:'https://example.com/sop/sales',checklist:['Collect data','Update sheet','Share report'],tags:['finance']}
];
const initialTasks=[
{taskNo:'TASK-000001',title:'Design Instagram Feed Post',business:'SIA Jewels',department:'Graphic Design',assignees:['u2','u4'],watchers:['u1'],due:'2026-07-09',priority:'High',status:'Ready',estimated:30,actual:0,timer:false,teamId:'t1',parentId:null,checklist:[{text:'Open brief',done:true},{text:'Create design',done:false}],comments:[{by:'Sandhya',text:'Premium look chahiye'}],files:[{name:'brief-v1.pdf',version:1}],activity:['Task created','Assigned to Rahul and Neha'],archived:false,deleted:false,frequency:'Daily',sop:'https://example.com/sop/feed',custom:{Platform:'Instagram',Approval:false}}
];
const Auth=createContext();
function useAuth(){return useContext(Auth)}
function can(user,action,task){
 if(!user) return false; const scope=ROLES[user.role]; if(scope==='all') return true;
 if(action==='library'||action==='settings'||action==='employees') return false;
 if(!task) return ['dashboard','calendar','attendance'].includes(action);
 if(scope==='department') return task.department===user.department;
 if(scope==='team') return task.teamId===user.teamId || task.assignees.includes(user.id);
 return task.assignees.includes(user.id) || task.watchers.includes(user.id);
}
function visibleTasks(user,tasks){return tasks.filter(t=>!t.deleted && can(user,'task',t))}
function App(){
 const [user,setUser]=useState(employees[0]); const [dark,setDark]=useState(false); const [page,setPage]=useState('dashboard'); const [tasks,setTasks]=useState(initialTasks); const [library,setLibrary]=useState(librarySeed); const [query,setQuery]=useState('');
 const value={user,setUser,tasks,setTasks,library,setLibrary,query,setQuery,dark,setDark};
 return <Auth.Provider value={value}><div className={dark?'app dark':'app'}><Sidebar page={page} setPage={setPage}/><main><Topbar/><div className="content">{page==='dashboard'&&<Dashboard/>}{page==='business'&&<Master title="Business Management" items={businesses}/>} {page==='departments'&&<Master title="Department Management" items={departments}/>} {page==='employees'&&<Employees/>}{page==='library'&&<TaskLibrary/>}{page==='tasks'&&<TaskBoard/>}{page==='attendance'&&<Attendance/>}{page==='calendar'&&<Calendar/>}{page==='reports'&&<Reports/>}{page==='settings'&&<SettingsPage/>}</div></main></div></Auth.Provider>
}
function Sidebar({page,setPage}){const {user}=useAuth(); const nav=[['dashboard',LayoutDashboard,'Dashboard'],['business',Briefcase,'Businesses'],['departments',Layers,'Departments'],['employees',Users,'Employees'],['library',Shield,'Task Library'],['tasks',CheckSquare,'Tasks'],['attendance',Clock,'Attendance'],['calendar',CalendarDays,'Calendar'],['reports',BarChart3,'Reports'],['settings',Settings,'Settings']]; return <aside><h2>HRIDHIYAM OS</h2><p className="version">v1.0 modular</p>{nav.filter(([id])=>can(user,id)).map(([id,Icon,label])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><Icon size={18}/>{label}</button>)}</aside>}
function Topbar(){const {user,setUser,query,setQuery,dark,setDark}=useAuth(); return <header><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Global search tasks, employees, tags..."/></div><select value={user.id} onChange={e=>setUser(employees.find(x=>x.id===e.target.value))}>{employees.map(e=><option value={e.id} key={e.id}>{e.name} — {e.role}</option>)}</select><button onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><button><LogOut/></button></header>}
function Dashboard(){const {user,tasks}=useAuth(); const vt=visibleTasks(user,tasks); const data=statuses.map(s=>({name:s,value:vt.filter(t=>t.status===s).length})); return <><h1>Dashboard</h1><div className="cards"><Card title="Visible Tasks" value={vt.length}/><Card title="Pending" value={vt.filter(t=>t.status!=='Completed').length}/><Card title="Completed" value={vt.filter(t=>t.status==='Completed').length}/><Card title="Overdue" value={vt.filter(t=>t.due<'2026-07-08'&&t.status!=='Completed').length}/></div><section className="grid2"><Panel title="Tasks by Status"><ResponsiveContainer height={240}><PieChart><Pie data={data} dataKey="value" nameKey="name" outerRadius={85} label>{data.map((_,i)=><Cell key={i}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></Panel><Panel title="Permission Scope"><p><b>{user.role}</b> login active. Access is checked by permission function, not only UI hide.</p><p>Employee = self tasks only. Team Lead = own team. Manager = department. Admin/Founder = full.</p></Panel></section></>}
function Card({title,value}){return <div className="card"><span>{title}</span><b>{value}</b></div>}
function Panel({title,children}){return <section className="panel"><h3>{title}</h3>{children}</section>}
function TaskLibrary(){const {user,library,setLibrary}=useAuth(); if(!can(user,'library')) return <Denied/>; return <><h1>Master Task Library</h1><button className="primary" onClick={()=>setLibrary([...library,{...librarySeed[0],id:'LIB-'+String(library.length+1).padStart(4,'0'),name:'New Template Task'}])}><Plus/> Add Template</button><Table rows={library} cols={['id','name','business','department','role','frequency','priority','estimated','dependsOn','sop']}/><TaskGenerator/></>}
function TaskGenerator(){const {library,tasks,setTasks}=useAuth(); const [f,setF]=useState({business:'SIA Jewels',department:'Graphic Design',frequency:'Daily',employee:'u2',days:1}); function gen(){let list=library.filter(x=>x.business===f.business&&x.department===f.department&&x.frequency===f.frequency); const newTasks=list.map((x,i)=>({taskNo:'TASK-'+String(tasks.length+i+1).padStart(6,'0'),title:x.name,business:x.business,department:x.department,assignees:[f.employee],watchers:['u1'],due:'2026-07-09',priority:x.priority,status:'Ready',estimated:x.estimated,actual:0,timer:false,teamId:employees.find(e=>e.id===f.employee)?.teamId,parentId:null,checklist:x.checklist.map(c=>({text:c,done:false})),comments:[],files:[],activity:['Generated from library'],archived:false,deleted:false,frequency:x.frequency,sop:x.sop,custom:{}})); setTasks([...tasks,...newTasks]); alert(newTasks.length+' tasks generated');}
return <Panel title="Task Generator"><div className="formrow"><select onChange={e=>setF({...f,business:e.target.value})}>{businesses.map(x=><option>{x}</option>)}</select><select onChange={e=>setF({...f,department:e.target.value})}>{departments.map(x=><option>{x}</option>)}</select><select onChange={e=>setF({...f,frequency:e.target.value})}>{frequencies.map(x=><option>{x}</option>)}</select><select onChange={e=>setF({...f,employee:e.target.value})}>{employees.map(x=><option value={x.id}>{x.name}</option>)}</select><button className="primary" onClick={gen}>Generate Tasks</button></div></Panel>}
function TaskBoard(){const {user,tasks,setTasks,query}=useAuth(); const [filter,setFilter]=useState({status:'All',priority:'All'}); let vt=visibleTasks(user,tasks).filter(t=>(filter.status==='All'||t.status===filter.status)&&(filter.priority==='All'||t.priority===filter.priority)&&(t.title.toLowerCase().includes(query.toLowerCase())||t.taskNo.toLowerCase().includes(query.toLowerCase()))); function upd(no,patch){setTasks(tasks.map(t=>t.taskNo===no?{...t,...patch,activity:[...t.activity,`${user.name} updated ${Object.keys(patch).join(', ')}`]}:t))} function exp(type){const rows=vt.map(t=>({Task:t.taskNo,Title:t.title,Status:t.status,Priority:t.priority,Due:t.due})); if(type==='xlsx'){const ws=XLSX.utils.json_to_sheet(rows); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,'Tasks'); XLSX.writeFile(wb,'tasks-export.xlsx')} if(type==='csv'){XLSX.writeFile({SheetNames:['Tasks'],Sheets:{Tasks:XLSX.utils.json_to_sheet(rows)}},'tasks-export.csv')} if(type==='pdf'){const doc=new jsPDF(); autoTable(doc,{head:[Object.keys(rows[0]||{})],body:rows.map(Object.values)}); doc.save('tasks-export.pdf')}} return <><h1>Task Management</h1><div className="toolbar"><select onChange={e=>setFilter({...filter,status:e.target.value})}><option>All</option>{statuses.map(x=><option>{x}</option>)}</select><select onChange={e=>setFilter({...filter,priority:e.target.value})}><option>All</option>{priorities.map(x=><option>{x}</option>)}</select><button onClick={()=>exp('xlsx')}><Download/> Excel</button><button onClick={()=>exp('csv')}>CSV</button><button onClick={()=>exp('pdf')}>PDF</button><button><Upload/> Bulk Import</button></div><div className="taskgrid">{vt.map(t=><TaskCard key={t.taskNo} t={t} upd={upd}/>)}</div></>}
function TaskCard({t,upd}){return <article className="task"><div><b>{t.taskNo}</b><span className="pill">{t.priority}</span></div><h3>{t.title}</h3><p>{t.business} • {t.department}</p><p>Assignees: {t.assignees.map(id=>employees.find(e=>e.id===id)?.name).join(', ')}</p><select value={t.status} onChange={e=>upd(t.taskNo,{status:e.target.value})}>{statuses.map(s=><option>{s}</option>)}</select><div className="actions"><button onClick={()=>upd(t.taskNo,{timer:true})}><Play size={16}/>Start</button><button onClick={()=>upd(t.taskNo,{timer:false,actual:t.actual+5})}><Pause size={16}/>Pause</button><button onClick={()=>upd(t.taskNo,{archived:true})}><Archive size={16}/></button><button onClick={()=>upd(t.taskNo,{deleted:true})}><Trash2 size={16}/></button></div><small>Est {t.estimated}m / Actual {t.actual}m</small><details><summary><History size={14}/> Timeline, files, comments</summary><ul>{t.activity.map(a=><li>{a}</li>)}</ul><p><Paperclip size={14}/> Files: {t.files.map(f=>`${f.name} v${f.version}`).join(', ')||'No files'}</p><p><MessageSquare size={14}/> Comments: {t.comments.map(c=>c.text).join(', ')||'No comments'}</p><p>SOP: <a href={t.sop}>Open SOP</a></p></details></article>}
function Employees(){return <><h1>Employee Management</h1><Table rows={employees} cols={['id','name','role','department','business','teamId']}/></>}
function Attendance(){const [inAt,setIn]=useState(null);return <><h1>Attendance</h1><Panel title="Today"><div className="toolbar"><button onClick={()=>setIn(new Date().toLocaleTimeString())}>Check In</button><button>Break Start</button><button>Break End</button><button>Check Out</button></div><p>Check In: {inAt||'-'} | Late Entry, Overtime and history ready for backend.</p></Panel></>}
function Calendar(){const {tasks,user}=useAuth();return <><h1>Calendar</h1><Table rows={visibleTasks(user,tasks)} cols={['taskNo','title','due','status','priority']}/></>}
function Reports(){const {tasks,user}=useAuth(); const vt=visibleTasks(user,tasks); return <><h1>Reports</h1><Panel title="Department Performance"><ResponsiveContainer height={260}><BarChart data={departments.map(d=>({department:d,tasks:vt.filter(t=>t.department===d).length}))}><XAxis dataKey="department"/><YAxis/><Tooltip/><Bar dataKey="tasks"/></BarChart></ResponsiveContainer></Panel></>}
function SettingsPage(){return <><h1>Settings</h1><div className="grid2"><Master title="Roles" items={Object.keys(ROLES)}/><Master title="Statuses" items={statuses}/><Master title="Priorities" items={priorities}/><Master title="Frequencies" items={frequencies}/></div></>}
function Master({title,items}){return <Panel title={title}><ul className="list">{items.map(i=><li>{i}<button>Edit</button></li>)}</ul></Panel>}
function Table({rows,cols}){return <div className="table"><table><thead><tr>{cols.map(c=><th>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{cols.map(c=><td>{Array.isArray(r[c])?r[c].join(', '):String(r[c]??'')}</td>)}</tr>)}</tbody></table></div>}
function Denied(){return <Panel title="Access Denied"><p>Is section ka access aapke role ke paas nahi hai.</p></Panel>}
createRoot(document.getElementById('root')).render(<App/>);
